version: 1.0.{build}
image: Visual Studio 2017

artifacts:
  - path: cert\*.pfx
    name: certificates

install:
  - ps: Write-Host Server version $(gp 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').BuildLabEx
  - cmd: docker version
  - ps: Install-Module -Name Pester -Force -SkipPublisherCheck

build_script:
  - ps: .\Build.ps1

test_script:
  - ps: |
      $testsResultsFile = ".\TestResults.xml"
      $testResults = Invoke-Pester -Script .\Test.ps1 -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
      If ($testResults.FailedCount -gt 0) { 
        throw "$($testResults.FailedCount) tests failed."
      }
